sudo: required
language: scala
scala:
  - 2.11.8
install:
  - imllib=$(pwd)
  - cd /opt/
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
  - tar -xzf spark-1.6.0-bin-hadoop2.6.tgz
  - wget http://mirror.nexcess.net/apache/hadoop/common/hadoop-2.6.5/hadoop-2.6.5.tar.gz
  - tar -xzf hadoop-2.6.5.tar.gz
  - cd ${imllib}
  - cp ./travis/spark-env.sh /opt/spark-1.6.0-bin-hadoop2.6/conf/
  - cp ./travis/core-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/hdfs-site.xml /opt/hadoop-2.6.5/etc/hadoop/
  - cp ./travis/mapred-site.xml /opt/hadoop-2.6.5/etc/hadoop/
#  - cp ./travis/yarn-site.xml /opt/hadoop-2.6.5/etc/hadoop/
#before_script:
#  - "export JAVA_OPTS=-Xmx512m"
#cache:
#  directories:
#  - $HOME/.m2
script:
  - sbt clean package
  - sudo -E ./travis/configssh.sh
  - sudo -E ./travis/restart-hadoop-spark.sh
#  - /opt/hadoop-2.6.5/bin/yarn node -list 2
  - jps
  - hdfs dfs -put ./data/* /
  - sudo -E ./bin/runFM.sh
